name: Deploy to Production

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v4

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync to production
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          PROD_DEPLOY_HOST: ${{ secrets.PROD_DEPLOY_HOST }}
          APP_DIR: ${{ secrets.APP_DIR }}
        run: |
          rsync -avz --delete ./ \
          $DEPLOY_USER@$PROD_DEPLOY_HOST:$APP_DIR/

      - name: Restart production service
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          PROD_DEPLOY_HOST: ${{ secrets.PROD_DEPLOY_HOST }}
        run: |
          ssh -o StrictHostKeyChecking=no \
          $DEPLOY_USER@$PROD_DEPLOY_HOST "sudo systemctl restart myapp"

      - name: Production health check
        env:
          PROD_DEPLOY_HOST: ${{ secrets.PROD_DEPLOY_HOST }}
        run: |
          curl -fsS --max-time 10 http://$PROD_DEPLOY_HOST/health || exit 1
